-- GENERATED BY scripts/gen_ask_schema.py FROM scripts/ask_manifest.yml + the live database.
-- DO NOT EDIT. Regenerate with `make db-ask-gen`; tests/test_ask_schema_sync.py fails
-- the build if this file differs by one byte from a fresh regeneration.
--
-- 61 table-backed views + 4 curated views = 65 objects.
-- Views are OWNER-RIGHTS (the PostgreSQL default), never security_invoker: that is what
-- lets f1_ask hold no privilege at all on any base table. They carry no row predicates.
--
-- Excluded at the GRANT level, so a compromised model gets `permission denied`:
--   ask_answer_cache       Same: cached rows and headlines keyed by other people's questions.
--   ask_query_log          Holds other fans' questions — untrusted free text a stranger typed. Making it queryable would turn the ask box into a read channel for every payload ever submitted.
--   circuit_layout         Rendering geometry (rotation, reference session). Answers no question a fan asks.
--   data_release           Push bookkeeping for the production database (when the laptop last synced, how many rows). Operational, not a fact about a race; the site footer reads it directly.
--   ingest_runs            hostname is the owner's machine and cli_args carries local cache paths; error carries Python tracebacks with absolute /Users/ paths. The one real PII surface here.
--   lap_exclusion_report   Per-lap audit plumbing. The clean-lap story is laps.is_representative and ask.lap_status, both of which are queryable.
--   lap_telemetry          10 Hz channel arrays, ~626 values per column per row. The planner prices unnest() at 10 rows: a query over these reads 2.2M samples while reporting a total cost of ~1,800, so MAX_PLAN_COST and MAX_PLAN_ROWS cannot see it (measured: 53,240 estimated against 3,332,582 actual, 62.6x under). A single SELECT of one array column also blows the response byte cap. The answerable half is ask.lap_telemetry_summary and ask.lap_corner_speeds, which are honest scalar rows.
--   mode2_fit_run          Fit internals; invites the model to answer a fan's question with a diagnostic.
--   mode2_row_audit        Per-row residuals and exclusion reasons; same reason as mode2_fit_run.
--   race_report            Generated prose must not be laundered back in as data. Reports are served by the precomputed page path only.
--   session_ingests        Same error column plus warnings[] — raw exception text leaks module paths and filesystem layout. Replaced by the curated ask.session_health and ask.data_coverage.
--   wp_model_artifact      1.4 MB of pickled scikit-learn bytea. Useless to a fan, a liability in a browser, and a single SELECT blows the response budget.
--   wp_run                 Fit internals. An honest answer built on them needs statistical caveats the ask box cannot give.
-- Excluded at the column level:
--   assumption_sets.params
--   circuit_corners.x
--   circuit_corners.y
--   lap_corner_speeds.trail_duty
--   lap_telemetry_summary.s1_distance_m
--   lap_telemetry_summary.s2_distance_m
--   lap_telemetry_summary.n_gaps_over_50m

BEGIN;

CREATE SCHEMA IF NOT EXISTS ask;

-- 61 table-backed views

CREATE OR REPLACE VIEW ask.assumption_sets AS
  SELECT assumption_set_id,
         hash,
         created_at
    FROM public.assumption_sets;

CREATE OR REPLACE VIEW ask.circuit_corners AS
  SELECT circuit_key,
         year,
         corner_number,
         corner_letter,
         angle_deg,
         distance_m
    FROM public.circuit_corners;

CREATE OR REPLACE VIEW ask.circuit_odi AS
  SELECT circuit_key,
         assumption_set_id,
         races,
         passes,
         opportunities,
         raw_pass_rate,
         resid_mean,
         resid_shrunk,
         adj_pass_rate,
         odi,
         odi_lo,
         odi_hi
    FROM public.circuit_odi;

CREATE OR REPLACE VIEW ask.circuits AS
  SELECT circuit_key,
         short_name,
         location,
         country,
         lap_km
    FROM public.circuits;

CREATE OR REPLACE VIEW ask.compound_colours AS
  SELECT session_id,
         compound,
         colour
    FROM public.compound_colours;

CREATE OR REPLACE VIEW ask.compound_degradation AS
  SELECT session_id,
         assumption_set_id,
         compound,
         laps,
         slope_s_per_lap,
         intercept_s,
         x_min,
         x_max
    FROM public.compound_degradation;

CREATE OR REPLACE VIEW ask.constructor_standings AS
  SELECT year,
         after_round,
         team_id,
         team_name,
         team_colour,
         position,
         points,
         wins,
         podiums
    FROM public.constructor_standings;

CREATE OR REPLACE VIEW ask.degradation_fits AS
  SELECT session_id,
         assumption_set_id,
         driver_id,
         stint,
         team_id,
         compound,
         laps,
         deg_s_per_lap,
         deg_std_err,
         r2,
         fresh_pace_s
    FROM public.degradation_fits;

CREATE OR REPLACE VIEW ask.driver_season_summary AS
  SELECT year,
         driver_id,
         assumption_set_id,
         team_id,
         team_name,
         team_colour,
         races,
         points,
         wins,
         podiums,
         dnfs,
         championship_position,
         best_finish,
         avg_finish,
         avg_grid,
         mean_pace_rank,
         races_ranked
    FROM public.driver_season_summary;

CREATE OR REPLACE VIEW ask.driver_standings AS
  SELECT year,
         after_round,
         driver_id,
         team_id,
         team_name,
         team_colour,
         position,
         points,
         sprint_points,
         wins,
         podiums,
         races
    FROM public.driver_standings;

CREATE OR REPLACE VIEW ask.drivers AS
  SELECT driver_id,
         latest_code,
         latest_number,
         first_name,
         last_name,
         full_name,
         country_code,
         headshot_url
    FROM public.drivers;

CREATE OR REPLACE VIEW ask.events AS
  SELECT year,
         round,
         event_name,
         official_name,
         location,
         country,
         event_format,
         event_date,
         circuit_key
    FROM public.events;

CREATE OR REPLACE VIEW ask.fuel_sensitivity AS
  SELECT session_id,
         assumption_set_id,
         driver_id,
         fuel_effect_s_per_kg,
         rank,
         gap_s
    FROM public.fuel_sensitivity;

CREATE OR REPLACE VIEW ask.lap_corner_speeds AS
  SELECT session_id,
         driver_id,
         lap_number,
         corner_number,
         corner_letter,
         apex_speed_kph,
         apex_distance_m,
         entry_speed_kph,
         exit_speed_kph,
         brake_zone_idx,
         brake_point_m,
         brake_distance_m,
         throttle_point_m,
         time_in_corner_s,
         brake_release_m,
         brake_release_to_apex_m,
         brake_on_distance_m,
         trail_status
    FROM public.lap_corner_speeds;

CREATE OR REPLACE VIEW ask.lap_status AS
  SELECT session_id,
         lap_number,
         is_green,
         worst_status,
         drivers_affected,
         drivers_on_lap
    FROM public.lap_status;

CREATE OR REPLACE VIEW ask.lap_telemetry_summary AS
  SELECT session_id,
         driver_id,
         lap_number,
         top_speed_kph,
         min_speed_kph,
         full_throttle_pct,
         brake_pct,
         lift_pct,
         overlap_pct,
         n_brake_zones,
         n_gear_changes,
         drs_distance_m,
         track_length_m,
         n_samples,
         max_sample_gap_m
    FROM public.lap_telemetry_summary;

CREATE OR REPLACE VIEW ask.laps AS
  SELECT session_id,
         driver_id,
         lap_number,
         stint,
         compound,
         tyre_life,
         fresh_tyre,
         position,
         track_status,
         lap_time_s,
         session_time_s,
         lap_start_time_s,
         sector1_s,
         sector2_s,
         sector3_s,
         speed_i1,
         speed_i2,
         speed_fl,
         speed_st,
         pit_in_time_s,
         pit_out_time_s,
         is_accurate,
         deleted,
         deleted_reason,
         fastf1_generated,
         is_personal_best,
         excl_no_time,
         excl_in_lap,
         excl_out_lap,
         excl_not_green,
         excl_inaccurate,
         excl_deleted,
         passes_rules,
         is_outlier,
         is_representative,
         fuel_kg,
         fuel_penalty_s,
         lap_time_fc_s,
         gap_to_leader_s,
         interval_s,
         leader_driver_id,
         quali_segment,
         segment_source,
         is_push_lap,
         excl_disallowed,
         deleted_inferred
    FROM public.laps;

CREATE OR REPLACE VIEW ask.mode2_car_hazard AS
  SELECT fit_id,
         assumption_set_id,
         team_id,
         year,
         retirements,
         racing_laps,
         hazard_per_1000,
         hazard_lo,
         hazard_hi,
         hazard_car_only,
         hazard_car_lo,
         hazard_car_hi,
         rank_in_season,
         sufficient
    FROM public.mode2_car_hazard;

CREATE OR REPLACE VIEW ask.mode2_car_rating AS
  SELECT fit_id,
         assumption_set_id,
         team_id,
         year,
         gamma_pp,
         gamma_lo,
         gamma_hi,
         slope_pp,
         slope_lo,
         slope_hi,
         start_pp,
         end_pp,
         slope_significant,
         rank_in_season,
         component_id,
         basis,
         n_races
    FROM public.mode2_car_rating;

CREATE OR REPLACE VIEW ask.mode2_career_season AS
  SELECT fit_id,
         assumption_set_id,
         driver_id,
         year,
         team_id,
         actual_points,
         replay_points,
         replay_lo,
         replay_hi,
         avg_driver_points,
         avg_driver_p10,
         avg_driver_p90,
         contribution,
         contribution_lo,
         contribution_hi,
         mc_stderr,
         param_stderr,
         calibration_mae,
         basis,
         anchor_class,
         rounds_in_season,
         starts,
         teams
    FROM public.mode2_career_season;

CREATE OR REPLACE VIEW ask.mode2_component AS
  SELECT fit_id,
         assumption_set_id,
         component_id,
         label,
         n_drivers,
         n_cells,
         is_floating,
         driver_ids,
         cell_ids
    FROM public.mode2_component;

CREATE OR REPLACE VIEW ask.mode2_counterfactual AS
  SELECT fit_id,
         assumption_set_id,
         year,
         driver_id,
         team_id,
         replaced_driver_id,
         observed,
         points_p10,
         points_p50,
         points_p90,
         incumbent_actual,
         delta_p10,
         delta_p50,
         delta_p90,
         basis,
         cross_component,
         interaction_pp,
         calibration_mae
    FROM public.mode2_counterfactual;

CREATE OR REPLACE VIEW ask.mode2_driver_contrast AS
  SELECT fit_id,
         assumption_set_id,
         driver_a,
         driver_b,
         kind,
         delta_pp,
         delta_se,
         delta_lo,
         delta_hi,
         same_component,
         shared_cells,
         n_shared_races,
         n_races_a,
         n_races_b
    FROM public.mode2_driver_contrast;

CREATE OR REPLACE VIEW ask.mode2_driver_rating AS
  SELECT fit_id,
         assumption_set_id,
         driver_id,
         rating_pp,
         rating_lo,
         rating_hi,
         sd_within,
         sd_island,
         sd_total,
         frac_floating,
         evidence_share,
         anchor_class,
         basis,
         component_id,
         rank_in_component,
         n_races,
         n_cells,
         n_races_excluded
    FROM public.mode2_driver_rating;

CREATE OR REPLACE VIEW ask.mode2_driver_rating_history AS
  SELECT fit_id,
         assumption_set_id,
         driver_id,
         through_year,
         rating_pp,
         rating_lo,
         rating_hi,
         sd_total,
         anchor_class,
         n_races_cumulative,
         switched_this_year
    FROM public.mode2_driver_rating_history;

CREATE OR REPLACE VIEW ask.mode2_driver_skill AS
  SELECT fit_id,
         assumption_set_id,
         driver_id,
         skill,
         measured,
         value,
         value_lo,
         value_hi,
         unit,
         evidence_share,
         anchor_class,
         pct_field_below,
         not_measured_reason,
         n_obs
    FROM public.mode2_driver_skill;

CREATE OR REPLACE VIEW ask.mode2_points_calib AS
  SELECT fit_id,
         assumption_set_id,
         year,
         slope_theta_per_pp,
         intercept,
         r2,
         resid_sd,
         temperature,
         sd_ratio_sim_actual,
         replay_mae_points,
         replay_corr,
         n_entries
    FROM public.mode2_points_calib;

CREATE OR REPLACE VIEW ask.mode2_quali_row_audit AS
  SELECT fit_id,
         assumption_set_id,
         session_id,
         driver_id,
         team_id,
         year,
         round,
         kind,
         included,
         exclude_reason,
         y_pp,
         best_s
    FROM public.mode2_quali_row_audit;

CREATE OR REPLACE VIEW ask.optimal_stint AS
  SELECT session_id,
         assumption_set_id,
         compound,
         n_fits,
         slope_s_per_lap,
         slope_q1,
         slope_q3,
         pit_loss_s,
         pit_loss_source,
         optimal_laps,
         optimal_laps_lo,
         optimal_laps_hi,
         actual_median_laps,
         slope_source
    FROM public.optimal_stint;

CREATE OR REPLACE VIEW ask.pace_ranking AS
  SELECT session_id,
         assumption_set_id,
         driver_id,
         rank,
         team_id,
         clean_laps,
         median_pace_s,
         best_pace_s,
         iqr_s,
         gap_s,
         gap_pct,
         box_whisker_lo_s,
         box_q1_s,
         box_q3_s,
         box_whisker_hi_s,
         box_mean_s,
         sens_rank_lo,
         sens_rank_hi
    FROM public.pace_ranking;

CREATE OR REPLACE VIEW ask.pit_stops AS
  SELECT session_id,
         driver_id,
         stop_number,
         lap_in,
         lap_out,
         pit_in_time_s,
         pit_out_time_s,
         pit_lane_s,
         compound_in,
         compound_out
    FROM public.pit_stops;

CREATE OR REPLACE VIEW ask.preview_backtest AS
  SELECT year,
         round,
         assumption_set_id,
         driver_id,
         pred_kind,
         expected_position,
         pos_p10,
         pos_p90,
         actual_position,
         inside_interval
    FROM public.preview_backtest;

CREATE OR REPLACE VIEW ask.preview_finish_order AS
  SELECT year,
         round,
         assumption_set_id,
         driver_id,
         expected_position,
         pos_p10,
         pos_p90,
         p_win,
         p_podium,
         p_points,
         theta,
         dnf_rate,
         draws
    FROM public.preview_finish_order;

CREATE OR REPLACE VIEW ask.preview_round AS
  SELECT year,
         round,
         assumption_set_id,
         circuit_key,
         circuit_match,
         circuit_races,
         expected_total_laps,
         p_safety_car,
         sc_hazard_shrunk,
         p_vsc,
         expected_pit_loss_s,
         pit_loss_band_s,
         odi,
         odi_lo,
         odi_hi,
         backtest_spearman,
         backtest_grid_spearman,
         backtest_coverage,
         backtest_races,
         loco_brier,
         computed_at
    FROM public.preview_round;

CREATE OR REPLACE VIEW ask.quali_results AS
  SELECT session_id,
         driver_id,
         team_id,
         position,
         q1_s,
         q2_s,
         q3_s,
         best_s,
         best_segment,
         best_lap_number,
         segments_entered,
         knocked_out_in,
         set_a_time,
         gap_to_pole_s,
         gap_to_pole_pct,
         gap_to_pole_common_s,
         gap_to_pole_common_pct,
         gap_to_pole_segment,
         n_repr_laps,
         push_laps,
         times_source
    FROM public.quali_results;

CREATE OR REPLACE VIEW ask.quali_segment_times AS
  SELECT session_id,
         driver_id,
         segment,
         laps_run,
         repr_laps,
         push_laps,
         best_s,
         best_lap_number,
         gap_to_best_s,
         gap_to_best_pct,
         spread_s,
         sd_s,
         compound,
         tyre_life,
         wet_compound,
         verified
    FROM public.quali_segment_times;

CREATE OR REPLACE VIEW ask.quali_teammate_h2h AS
  SELECT session_id,
         team_id,
         driver_a,
         driver_b,
         segment,
         a_best_s,
         b_best_s,
         delta_s,
         delta_pct,
         comparable,
         classified_ahead,
         divergent,
         session_sd_s,
         below_noise
    FROM public.quali_teammate_h2h;

CREATE OR REPLACE VIEW ask.race_moment AS
  SELECT session_id,
         assumption_set_id,
         moment_idx,
         moment_type,
         lap_number,
         driver_id,
         other_driver_id,
         magnitude,
         magnitude_unit,
         severity,
         confidence,
         detail
    FROM public.race_moment;

CREATE OR REPLACE VIEW ask.results AS
  SELECT session_id,
         driver_id,
         position,
         classified_position,
         grid_position,
         points,
         status,
         laps_completed,
         result_time_s
    FROM public.results;

CREATE OR REPLACE VIEW ask.season_quali_h2h AS
  SELECT year,
         kind,
         team_id,
         driver_a,
         driver_b,
         sessions_counted,
         a_wins,
         b_wins,
         deltas_counted,
         median_delta_s,
         median_delta_pct,
         mad_delta_pct,
         sessions_caveated
    FROM public.season_quali_h2h;

CREATE OR REPLACE VIEW ask.seasons AS
  SELECT year,
         scheduled_rounds,
         ingested_rounds,
         standings_after_round,
         assumption_set_id,
         mixed_assumption_sets,
         has_sprint_results,
         recomputed_at
    FROM public.seasons;

CREATE OR REPLACE VIEW ask.session_entries AS
  SELECT session_id,
         driver_id,
         team_id,
         code,
         driver_number,
         line_style,
         line_style_source
    FROM public.session_entries;

CREATE OR REPLACE VIEW ask.session_teams AS
  SELECT session_id,
         team_id,
         team_name,
         colour,
         colour_source
    FROM public.session_teams;

CREATE OR REPLACE VIEW ask.sessions AS
  SELECT session_id,
         year,
         round,
         kind,
         name,
         start_utc,
         total_laps,
         winner_driver_id,
         fastest_pace_driver_id
    FROM public.sessions;

CREATE OR REPLACE VIEW ask.sim_circuit_hazard AS
  SELECT circuit_key,
         assumption_set_id,
         recomputed_at,
         races,
         laps,
         sc_episodes,
         vsc_episodes,
         sc_hazard,
         vsc_hazard,
         pit_loss_circuit_s,
         pooled_races,
         sc_hazard_pooled,
         vsc_hazard_pooled,
         sc_start_p,
         vsc_start_p,
         sc_dur_mean,
         vsc_dur_mean,
         pit_loss_pooled_s,
         pit_loss_pooled_mad_s,
         sc_pit_factor_pooled,
         vsc_pit_factor_pooled
    FROM public.sim_circuit_hazard;

CREATE OR REPLACE VIEW ask.sim_compound_params AS
  SELECT session_id,
         assumption_set_id,
         compound,
         laps,
         age_max,
         offset_s,
         offset_se,
         deg_raw_s_per_lap,
         deg_s_per_lap,
         deg_se,
         deg_negative,
         stint_tau_level_s,
         stint_tau_slope,
         stint_tau_source,
         stints_used
    FROM public.sim_compound_params;

CREATE OR REPLACE VIEW ask.sim_driver_compound AS
  SELECT session_id,
         assumption_set_id,
         driver_id,
         compound,
         laps,
         dc_offset_s,
         dc_se
    FROM public.sim_driver_compound;

CREATE OR REPLACE VIEW ask.sim_driver_params AS
  SELECT session_id,
         assumption_set_id,
         driver_id,
         laps_fit,
         base_s,
         base_se,
         noise_sd_s,
         laps_completed,
         laps_timed,
         laps_modelled,
         unmodelled_laps,
         stops,
         simulable,
         not_simulable_reason,
         real_total_s,
         real_total_fc_s,
         real_fuel_s,
         sim_total_fc_s,
         misfit_rep_s,
         misfit_pit_s,
         misfit_lap1_s,
         unmodelled_s,
         badge
    FROM public.sim_driver_params;

CREATE OR REPLACE VIEW ask.sim_race_params AS
  SELECT session_id,
         assumption_set_id,
         total_laps,
         ref_compound,
         laps_fit,
         drivers_fit,
         r2,
         resid_sd_s,
         resid_mad_s,
         design_cond,
         evo_s_per_lap,
         evo_se,
         param_names,
         param_mean,
         param_chol,
         field_delta_s,
         field_delta_cars,
         start_penalty_s,
         pit_loss_s,
         pit_loss_mad_s,
         pit_loss_n,
         pit_loss_samples_s,
         sc_pit_samples_s,
         vsc_pit_samples_s,
         sc_pit_factor_race,
         vsc_pit_factor_race,
         stint_coverage_80,
         n_sc_laps,
         n_vsc_laps,
         n_red_laps
    FROM public.sim_race_params;

CREATE OR REPLACE VIEW ask.stints AS
  SELECT session_id,
         driver_id,
         stint,
         compound,
         start_lap,
         end_lap,
         laps
    FROM public.stints;

CREATE OR REPLACE VIEW ask.teammate_deltas AS
  SELECT session_id,
         assumption_set_id,
         team_id,
         faster_driver_id,
         slower_driver_id,
         gap_s,
         gap_pct,
         laps_compared
    FROM public.teammate_deltas;

CREATE OR REPLACE VIEW ask.teammate_h2h AS
  SELECT year,
         driver_id,
         teammate_driver_id,
         assumption_set_id,
         team_id,
         races_paired,
         pace_wins,
         pace_losses,
         mean_signed_gap_pct,
         median_signed_gap_pct,
         finish_wins,
         finish_losses,
         grid_wins,
         grid_losses,
         points_for,
         points_against
    FROM public.teammate_h2h;

CREATE OR REPLACE VIEW ask.teams AS
  SELECT team_id,
         latest_name
    FROM public.teams;

CREATE OR REPLACE VIEW ask.title_clinch AS
  SELECT year,
         after_round,
         assumption_set_id,
         driver_id,
         points_now,
         max_available,
         max_possible_total,
         leader_points,
         is_eliminated,
         eliminated_at_round,
         has_clinched,
         clinch_margin_needed,
         swing_needed,
         clinch_position,
         earliest_clinch_round,
         next_round_has_sprint,
         race_points_max,
         sprint_points_max,
         has_fastest_lap_bonus
    FROM public.title_clinch;

CREATE OR REPLACE VIEW ask.title_odds AS
  SELECT year,
         after_round,
         assumption_set_id,
         driver_id,
         p_title,
         p_title_lo,
         p_title_hi,
         mc_stderr,
         p_top3,
         expected_points,
         points_p10,
         points_p90,
         theta,
         dnf_rate,
         is_shrunk_to_prior,
         draws
    FROM public.title_odds;

CREATE OR REPLACE VIEW ask.track_status_events AS
  SELECT session_id,
         event_idx,
         session_time_s,
         status,
         message
    FROM public.track_status_events;

CREATE OR REPLACE VIEW ask.weather_samples AS
  SELECT session_id,
         sample_idx,
         session_time_s,
         air_temp,
         humidity,
         pressure,
         rainfall,
         track_temp,
         wind_direction,
         wind_speed
    FROM public.weather_samples;

CREATE OR REPLACE VIEW ask.wp_lap_probability AS
  SELECT session_id,
         assumption_set_id,
         driver_id,
         lap_number,
         pred_kind,
         fold_index,
         p_win_raw,
         p_win,
         degraded
    FROM public.wp_lap_probability;

CREATE OR REPLACE VIEW ask.wp_metrics AS
  SELECT assumption_set_id,
         scope,
         variant,
         n_rows,
         n_races,
         brier,
         log_loss,
         brier_baseline_pos,
         brier_baseline_lead,
         brier_fold_min,
         brier_fold_median,
         brier_fold_max,
         note
    FROM public.wp_metrics;

CREATE OR REPLACE VIEW ask.wp_reliability_bin AS
  SELECT assumption_set_id,
         scope,
         variant,
         bin_index,
         bin_lo,
         bin_hi,
         n_rows,
         n_wins,
         mean_predicted,
         observed_rate,
         observed_lo,
         observed_hi
    FROM public.wp_reliability_bin;

CREATE OR REPLACE VIEW ask.wp_swing AS
  SELECT session_id,
         assumption_set_id,
         lap_number,
         swing_mass,
         cause,
         mover_driver_id,
         mover_p_before,
         mover_p_after,
         rank_in_race
    FROM public.wp_swing;

-- 4 curated views

CREATE OR REPLACE VIEW ask.session_health AS
  SELECT si.session_id, s.year, s.round, s.kind, s.name, si.status, si.analytics_status,
         si.raw_laps, si.clean_laps, si.total_laps,
         coalesce(array_length(si.warnings, 1), 0) AS warning_count
    FROM public.session_ingests si
    JOIN public.sessions s USING (session_id);

CREATE OR REPLACE VIEW ask.data_coverage AS
  SELECT year,
         count(*) FILTER (WHERE status = 'ok')      AS sessions_ok,
         count(*) FILTER (WHERE status = 'partial') AS sessions_partial,
         min(round) AS first_round,
         max(round) AS last_round
    FROM ask.session_health
   GROUP BY year;

CREATE OR REPLACE VIEW ask.race_index AS
  SELECT s.session_id, s.year, s.round, s.kind, s.name AS session_name,
         e.event_name, e.location, e.country,
         c.short_name AS circuit_short_name, c.circuit_key
    FROM public.sessions s
    JOIN public.events e USING (year, round)
    JOIN public.circuits c USING (circuit_key);

CREATE OR REPLACE VIEW ask.driver_index AS
  SELECT d.driver_id, d.latest_code, d.full_name, d.first_name, d.last_name, d.country_code
    FROM public.drivers d;

-- The allowlist IS the grant: 65 objects, named one by one.

DO $ask_grant$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'f1_ask') THEN
    EXECUTE $g$GRANT USAGE ON SCHEMA ask TO f1_ask$g$;
    EXECUTE $g$GRANT SELECT ON
           ask.assumption_sets,
           ask.circuit_corners,
           ask.circuit_odi,
           ask.circuits,
           ask.compound_colours,
           ask.compound_degradation,
           ask.constructor_standings,
           ask.degradation_fits,
           ask.driver_season_summary,
           ask.driver_standings,
           ask.drivers,
           ask.events,
           ask.fuel_sensitivity,
           ask.lap_corner_speeds,
           ask.lap_status,
           ask.lap_telemetry_summary,
           ask.laps,
           ask.mode2_car_hazard,
           ask.mode2_car_rating,
           ask.mode2_career_season,
           ask.mode2_component,
           ask.mode2_counterfactual,
           ask.mode2_driver_contrast,
           ask.mode2_driver_rating,
           ask.mode2_driver_rating_history,
           ask.mode2_driver_skill,
           ask.mode2_points_calib,
           ask.mode2_quali_row_audit,
           ask.optimal_stint,
           ask.pace_ranking,
           ask.pit_stops,
           ask.preview_backtest,
           ask.preview_finish_order,
           ask.preview_round,
           ask.quali_results,
           ask.quali_segment_times,
           ask.quali_teammate_h2h,
           ask.race_moment,
           ask.results,
           ask.season_quali_h2h,
           ask.seasons,
           ask.session_entries,
           ask.session_teams,
           ask.sessions,
           ask.sim_circuit_hazard,
           ask.sim_compound_params,
           ask.sim_driver_compound,
           ask.sim_driver_params,
           ask.sim_race_params,
           ask.stints,
           ask.teammate_deltas,
           ask.teammate_h2h,
           ask.teams,
           ask.title_clinch,
           ask.title_odds,
           ask.track_status_events,
           ask.weather_samples,
           ask.wp_lap_probability,
           ask.wp_metrics,
           ask.wp_reliability_bin,
           ask.wp_swing,
           ask.session_health,
           ask.data_coverage,
           ask.race_index,
           ask.driver_index
      TO f1_ask$g$;
  ELSE
    RAISE NOTICE 'role f1_ask does not exist yet - run scripts/sql/0005_roles.sql, then re-run this file so the enumerated GRANT is applied';
  END IF;
END
$ask_grant$;

COMMIT;
